name: deploy_to_cocoapods 

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (skip actual pod trunk push)'
        required: false
        default: false
        type: boolean
      force_republish:
        description: 'Force republish even if version already exists (requires pod trunk push --overwrite)'
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Get last pods version
        id: tag
        run: |
          git fetch --tags 
          VERSION=$(git tag | sort -V | tail -1)
          echo "$VERSION"
          echo "LAST_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Deploy to Cocoapods
        env:
          LIB_VERSION: ${{ steps.tag.outputs.LAST_VERSION }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          DRY_RUN: ${{ inputs.dry_run }}
          FORCE_REPUBLISH: ${{ inputs.force_republish }}
        run: |
          echo "Git tag version: $LIB_VERSION"
          
          # Check if version already exists on CocoaPods
          echo "Checking if version $LIB_VERSION already exists on CocoaPods..."
          EXISTING_VERSIONS=$(pod trunk info AxeptioIOSSDK | grep -E "^ *- [0-9]+\.[0-9]+\.[0-9]+" | awk '{print $2}')
          
          if echo "$EXISTING_VERSIONS" | grep -q "^${LIB_VERSION}$"; then
            if [ "$FORCE_REPUBLISH" = "true" ]; then
              echo "⚠️  Version $LIB_VERSION already exists on CocoaPods, but force_republish is enabled."
            else
              echo "✅ Version $LIB_VERSION already exists on CocoaPods. Skipping publish."
              echo "💡 To force republish, run with force_republish=true"
              exit 0
            fi
          fi
          
          echo "Version $LIB_VERSION not found on CocoaPods. Proceeding with validation and publish..."
          
          pod lib lint --allow-warnings
          
          if [ "$DRY_RUN" = "true" ]; then
            echo "=== DRY-RUN MODE ==="
            echo "Current published versions on CocoaPods:"
            echo "$EXISTING_VERSIONS" | head -5
            echo ""
            echo "Version to be published: $LIB_VERSION"
            if [ "$FORCE_REPUBLISH" = "true" ]; then
              echo "Would run: pod trunk push AxeptioIOSSDK.podspec --allow-warnings --overwrite"
            else
              echo "Would run: pod trunk push AxeptioIOSSDK.podspec --allow-warnings"
            fi
          else
            if [ "$FORCE_REPUBLISH" = "true" ]; then
              echo "Force republishing with --overwrite flag..."
              pod trunk push AxeptioIOSSDK.podspec --allow-warnings --overwrite
            else
              pod trunk push AxeptioIOSSDK.podspec --allow-warnings
            fi
          fi