name: deploy_to_cocoapods 

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (skip actual pod trunk push)'
        required: false
        default: false
        type: boolean

jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Get last pods version
        id: tag
        run: |
          git fetch --tags 
          VERSION=`git tag | sort -V | tail -1`
          echo "$VERSION"
          echo "LAST_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Deploy to Cocoapods
        env:
          LIB_VERSION: ${{ steps.tag.outputs.LAST_VERSION }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          DRY_RUN: ${{ inputs.dry_run }}
        run: |
          echo "Git tag version: $LIB_VERSION"
          pod lib lint --allow-warnings
          if [ "$DRY_RUN" = "true" ]; then
            echo "=== DRY-RUN MODE ==="
            echo "Current published version on CocoaPods:"
            pod trunk info AxeptioIOSSDK | grep -E "^\s+- [0-9]+\.[0-9]+\.[0-9]+" | head -1 | awk '{print $2}'
            echo ""
            echo "Version to be published: $LIB_VERSION"
            echo "Would run: pod trunk push AxeptioIOSSDK.podspec --allow-warnings"
          else
            pod trunk push AxeptioIOSSDK.podspec --allow-warnings
          fi